swagger: '2.0'
host: 'localhost:8080'
basePath: '/v1'
schemes:
  - http
  - https
info:
  description: A SpiceAPI for extracting NAIF Spice Data
  version: "0.1.2"
  title: Pfeffernusse
  contact:
    email: jlaura@usgs.gov
  license:
    name: UnLicense
    url: 'http://unlicense.org/'
paths:
  /pds/:
    post:
      summary: Converts Image Labels to ISDs
      operationId: create_isd
      x-swagger-router-controller: app.controllers.isd
      description: Adds an item to the system
      produces:
        - application/json
      responses:
        '200':
          description: 'Successful Label Translation'
          schema:
            $ref: '#/definitions/ISD200'
        '400':
          description: 'invalid input, object invalid'
      parameters:
        - name: label
          in: body
          required: true
          schema:
            $ref: '#/definitions/request_ISD'


definitions:
  optical_distortion:
    type: object
    additionalProperties: false
    maxProperties: 1
    minProperties: 0
    properties:
      transverse:
        type: object
        properties:
          x:
            type: array
            items:
              type: number
              minLength: 2
              maxLength: 10
          y:
            type: array
            items:
              type: number
              minLength: 2
              maxLength: 10
      radial:
        type: object
        properties:
          coefficients:
            type: array
            items:
              type: number
              description: Each coefficient used for the distortion equation in order
                of increasing degrees.
              minLength: 2
              maxLength: 10
  XYZ:
    type: object
    title: XYZ Position or Velocity
    description: An object to hold the x,y,z position or velocity of an object in meters
    required:
      - x
      - y
      - z
    properties:
      x:
        type: number
      y:
        type: number
      z:
        type: number
  request_ISD:
    type: object
    properties:
      label:
        type: string
        format: uuid
  Quaternion:
    type: array
    title: Quaternion
    description: 'Each quaternion is of the general form: (scalar, vector component, vector component,vector component).The specific form used is that described in the NAIF Quaternions whitepaper under ''SPICE Quaternions'' available at: ftp: //naif.jpl.nasa.gov/pub/naif/misc/Quaternion_White_Paper/Quaternions_White_Paper.pdf'
    items:
      type: number
      minLength: 4
      maxLength: 4
  ISD200:
    title: Instrument Specification Definition
    description: The Instrument Specification Definition for Astro CSM
    type: object
    properties:
      detector_center:
        description: Center of the detector in pixel coordinates (line, sample)
        type: object
        required:
          - line
          - sample
        properties:
          line:
            type: number
          sample:
            type: number
        example:
          line: 100
          sample: 100.5
      center_ephemeris_time:
        description: The center ephemeris time of the image
        type: number
      starting_ephemeris_time:
        description: The starting ephemeris time of the image
        type: number
      focal_length_model:
        description: The static focal length or the information needed to model a variable
          focal length
        type: object
        properties:
          key:
            type: string
            description: A key to get information about time/temp dependent focal length
              models
          focal_length:
            type: number
            description: The focal length in mm
          focal_epsilon:
            type: number
            description: The uncertainty of the focal length in mm
        required:
        - focal_length
      image_lines:
        description: The number of lines in the image
        type: number
      image_samples:
        description: The the number of samples in the image
        type: number
      radii:
        description: The radii of the target in meters.
        type: object
        required:
          - semimajor
        properties:
          semimajor:
            type: number
          semiminor:
            type: number
        example:
          semimajor: 339600.2
          semiminor: 337600.2
      optical_distortion:
          $ref: '#/definitions/optical_distortion'
      starting_detector_sample:
        description: The sample on the detector where the data starts
        type: number
      starting_detector_line:
        description: The line on the detector where the data starts
        type: number
      focal2pixel_samples:
        description: Transformation x coefficients from focal plane (mm) to detector pixel
          coordinates
        type: array
        items:
          type: number
      focal2pixel_lines:
        description: Transformation y coefficients from focal plane (mm) to detector pixel
          coordinates
        type: array
        items:
          type: number
      sensor_location:
          description: "(X, Y, Z) location of sensor in body-fixed frame."
          type: array
          items:
            $ref: '#/definitions/XYZ'
      sensor_velocity:
        description: "(v_x, v_y, v_z) velocity of sensor in body-fixed frame."
        type: array
        items:
          $ref: '#/definitions/XYZ'
      sun_position:
        description: "(x, y,z) of the sun in body-fixed frame."
        type: array
        items:
          $ref: '#/definitions/XYZ'
      sun_velocity:
        description: "(v_x, v_y, v_z) velocity of sun in body-fixed frame."
        type: array
        items:
          $ref: '#/definitions/XYZ'
      sensor_orientation:
        description: Orientation of the sensor provided in quaternions
        type: array
        items:
          $ref: '#/definitions/Quaternion'
      line_scan_rate:
        description: The line rates of the detector map with the associated start line
          and time
        type: array
        items:
          type: array
          items:
            type: number
            default: "-1"
            description: The (start_line, line_start_time, exposure_time). The exposure
              time is in seconds and any non - provided values will be set to - 1.
            minLength: 3
            maxLength: 3
      detector_sample_summing:
        description: 'The summing in the sample-direction. A summing of 1 indicates no
          summing, summing of 2 indicates 2 pixel summing,4 indicates 4 pixel summing,
          etc '
        type: number
      detector_line_summing:
        description: The summing in the line-direction
        type: number
      apply_light_time_correction:
        description: A flag to indcate whether the light-time correction should be applied
        type: boolean
      number_of_ephemerides:
        description: The number of emphemeris points
        type: number
      number_of_quaternions:
        description: The number of quaternions
        type: number
      dt_ephemeris:
        description: The time between each ephemeris point.
        type: number
      t0_ephemeris:
        description: First ephemeris time - center image time
        type: number
      dt_quaternion:
        description: Time spacing of quaternions.
        type: number
      t0_quaternion:
        description: First quaternion time - center image time.
        type: number
      reference_height:
        description: Used for determining the intersection of the look vector with the
          ellipsoid, measured in meters
        type: object
        required:
          - minheight
          - maxheight
        properties:
          minheight:
            type: number
          maxheight:
            type: number
        example:
          minheight: 100
          maxheight: 1000
      interpolation_method:
        description: The type of interpolation method to use.
        type: string
        enum:
          - lagrange
    required:
      - focal_length_model
      - starting_ephemeris_time
      - reference_height
      - sensor_orientation
      - focal2pixel_lines
      - focal2pixel_samples
      - radii
      - image_samples
      - image_lines
      - starting_detector_sample
      - starting_detector_line
